### ISSUE TITLE
🐛Update-github-release abgebrochen

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/ci_tools#52]
## Description

Der Uploadprozess ist fehlgeschlagen mit dem Fehler:

```
[update-github-release]	No --version-tag given, versionTag set to: v5.14.0-alpha.3
[update-github-release]	
[update-github-release]	Option --assets was given: [
  'dist/electron/bpmn-studio-portable-5.14.0-alpha.3.exe',
  'dist/electron/bpmn-studio-setup-5.14.0-alpha.3.exe',
  'dist/electron/bpmn-studio-setup-5.14.0-alpha.3.exe.blockmap',
  'dist/electron/bpmn-studio-setup-5.14.0-alpha.3.zip',
  'dist/electron/bpmn-studio-setup-5.14.0-alpha.3.dmg',
  'dist/electron/bpmn-studio-setup-5.14.0-alpha.3.dmg.blockmap',
  'dist/electron/latest-mac.yml',
  'dist/electron/latest.yml'
]
[before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
[update-github-release]	Updating existing release for v5.14.0-alpha.3 ...
[update-github-release]	- Uploading 'dist/electron/bpmn-studio-portable-5.14.0-alpha.3.exe' ...
[update-github-release]	- Uploading 'dist/electron/bpmn-studio-setup-5.14.0-alpha.3.exe' ...
[update-github-release]	- Uploading 'dist/electron/bpmn-studio-setup-5.14.0-alpha.3.exe.blockmap' ...
[update-github-release]	- Uploading 'dist/electron/bpmn-studio-setup-5.14.0-alpha.3.zip' ...
[update-github-release]	- Uploading 'dist/electron/bpmn-studio-setup-5.14.0-alpha.3.dmg' ...
[update-github-release]	- Uploading 'dist/electron/bpmn-studio-setup-5.14.0-alpha.3.dmg.blockmap' ...
TypeError: Cannot read property 'length' of undefined
    at updateExistingRelease (/home/runner/work/bpmn-studio/bpmn-studio/node_modules/@process-engine/ci_tools/dist/commands/update-github-release.js:116:51)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Reproduction

https://github.com/process-engine/bpmn-studio/runs/467378070?check_suite_focus=true

## My setup

- `@process-engine/ci_tools@2.5.1`

**Comment by alexanderkasten** [comment]
Fixed by #58
